export const GET_RESOURCES = "GET_RESOURCES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SPECIFIED_RESOURCE = "GET_SPECIFIED_RESOURCE";
export const ADD_NEW_RESOURCE = "ADD_NEW_RESOURCE";